version: '3.9'
services:
  mongodb:
    image: mongo:6.0.1
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - './volumes/mongodb/data:/data'
  app:
    image: whitekarasu/inventori-kantor
    restart: unless-stopped
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=inventaris-docker
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - 3000:3000