name: deploy production

on:
  push:
    branches:
      - 'master' # hanya master

jobs:
  checking-feature:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: deploy
        run: echo "deployed to prod"